import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"></body>
      
        <nav  className=" text-2xl   bg-gray-400  gap-10   justify-between py-4  px-4 items-center  flex text-2x1 text-black">
          <div className="font-bold text-3xl">
    <h1>Profile</h1>
  </div>
          <div className="flex gap-6 items-center">
    <Link href="/" className="px-3 py-2 hover:bg-gray-200 rounded-lg transition-colors duration-300 ">Home</Link>
    <Link href="/About" className="px-3 py-2 hover:bg-gray-200 rounded-lg transition-colors duration-300">About</Link>
    <Link href="/project" className="px-3 py-2 hover:bg-gray-200 rounded-lg transition-colors duration-300">Projects</Link>
    <Link href="/contact" className="px-3 py-2 hover:bg-gray-200 rounded-lg transition-colors duration-300">Contact</Link>
  </div>
        </nav>
      
      <div>
        {children}
      </div>
    </html>
  );
}
